// import { Poppins } from "next/font/google/";
"use client";
import AdminNav from "./components/AdminNav";
import SideBar from "./components/SideBar";
import axios from "axios";
import FilesTable from "./components/FilesTable";
import { Poppins } from "next/font/google";
import { useState } from "react";
import Paginado from "./components/Pagination";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export default function Admin({ data }: any) {
  //--------------Paginado-----------------------
  const [currentPage, setCurrentPage] = useState(1);
  const [filesPerPage] = useState(10);
  const LastFile = currentPage * filesPerPage; //
  const FirstFile = LastFile - filesPerPage; //
  const currentFiles = data?.slice(FirstFile, LastFile);

  const paginado = (pageNumber: number) => {
    setCurrentPage(pageNumber);
  };

  //---------------------------------------------

  return (
    <div lang="en" className={poppins.className}>
      <AdminNav />
      <div className="flex bg-gray-200 h-screen">
        <SideBar />
        <div className="flex flex-col w-full">
          <div className=" m-4">
            <div>
              <FilesTable cotizacion={currentFiles} />
              <Paginado
                paginado={paginado}
                filesPerPage={filesPerPage}
                files={data}
                current={currentPage}
              />
            </div>
          </div>
          <div className="w-full bg-white h-full"></div>
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const API_KEY = "f8f1e0d6ae9924a3331ac71108507015abbf0369";
  const files = await axios.get(`http://localhost:3001/file?apikey=${API_KEY}`);
  const data = files.data;
  return { props: { data } };
}
